# Generated by Django 4.2.7 on 2025-06-21 16:11

from django.db import migrations, models
import django.db.models.deletion
import image_processor.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProcessingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageProcessingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to=image_processor.models.upload_to_images)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to=image_processor.models.upload_to_processed)),
                ('output_width', models.PositiveIntegerField(help_text='Width in pixels')),
                ('output_height', models.PositiveIntegerField(help_text='Height in pixels')),
                ('dimension_unit', models.CharField(choices=[('cm', 'Centimeters'), ('inch', 'Inches')], default='cm', max_length=4)),
                ('dimension_width', models.FloatField(blank=True, help_text='Physical width', null=True)),
                ('dimension_height', models.FloatField(blank=True, help_text='Physical height', null=True)),
                ('dpi', models.PositiveIntegerField(default=300, help_text='Dots per inch')),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='image_processor.imageprocessingsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
