# Generated by Django 4.2.7 on 2025-06-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprocessingrequest',
            name='dimension_unit',
            field=models.CharField(choices=[('pixels', 'Pixels'), ('cm', 'Centimeters'), ('inch', 'Inches')], default='pixels', max_length=10),
        ),
    ]
