# Generated by Django 4.2.7 on 2025-06-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0002_alter_imageprocessingrequest_dimension_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprocessingrequest',
            name='dimension_unit',
        ),
        migrations.AlterField(
            model_name='imageprocessingrequest',
            name='dimension_height',
            field=models.PositiveIntegerField(blank=True, help_text='Custom height in pixels', null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingrequest',
            name='dimension_width',
            field=models.PositiveIntegerField(blank=True, help_text='Custom width in pixels', null=True),
        ),
    ]
