# Generated by Django 4.2.7 on 2025-06-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0003_remove_dimension_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessingrequest',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('pixels', 'Pixels'), ('cm', 'Centimeters'), ('inch', 'Inches')], default='pixels', max_length=8),
        ),
        migrations.AlterField(
            model_name='imageprocessingrequest',
            name='dimension_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageprocessingrequest',
            name='dimension_width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
