# Generated by Django 4.2.7 on 2025-06-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0004_add_dimension_unit_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessingrequest',
            name='original_file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Original file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='imageprocessingrequest',
            name='original_height',
            field=models.PositiveIntegerField(blank=True, help_text='Original height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='imageprocessingrequest',
            name='original_width',
            field=models.PositiveIntegerField(blank=True, help_text='Original width in pixels', null=True),
        ),
    ]
