# Generated by Django 4.2.7 on 2025-06-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0005_imageprocessingrequest_original_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessingrequest',
            name='output_file_type',
            field=models.CharField(choices=[('jpg', 'JPG'), ('png', 'PNG'), ('webp', 'WebP'), ('bmp', 'BMP'), ('tiff', 'TIFF')], default='jpg', help_text='Output file format', max_length=4),
        ),
    ]
